on:
  push:
    branches:
      - feature/ci/cd-pipeline
  pull_request:
    branches:
      - feature/ci/cd-pipeline

permissions:
  contents: write

jobs:
  build:
    name: Build portable Windows artifact
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci
        shell: pwsh

      - name: Build portable artifact
        # run the single script requested by you
        shell: pwsh
        run: |
          Write-Host "Running npm run build:portable"
          npm run build:portable

      - name: List potential output folders (debug)
        shell: pwsh
        run: |
          $paths = @('portable','dist','out')
          foreach ($p in $paths) {
            if (Test-Path $p) {
              Write-Host "Contents of $p:"
              Get-ChildItem -Recurse -Force $p | ForEach-Object { Write-Host $_.FullName }
            } else {
              Write-Host "$p not found"
            }
          }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            portable/**
            dist/**
            out/**

  release:
    name: Create GitHub Release (only on push to main)
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: release_files

      - name: List release_files
        run: dir /s /b release_files || echo "no release files"

      - name: Create GitHub release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          files: release_files/**
