name: Build and Release Portable EXE

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    env:
      ELECTRON_VERSION: "38.3.0"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Extract version from tag
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          if ($tag -notmatch '^v\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$') { throw "Tag must look like v1.2.3 or v1.2.3-rc.1" }
          $version = $tag.TrimStart('v')
          "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Building version $version"

      - name: Set package.json version
        run: npm version $env:APP_VERSION --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Electron rebuild (better-sqlite3)
        run: npx electron-rebuild -f -w better-sqlite3 -v $env:ELECTRON_VERSION

      - name: Build portable exe
        run: npm run build:portable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-exe
          path: dist/STC*.exe
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/STC*.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
