on:
  push:
    branches:
      - feature/ci/cd-pipeline
  pull_request:
    branches:
      - feature/ci/cd-pipeline

permissions:
  contents: write   # required for creating releases/assets with GITHUB_TOKEN

jobs:
  build:
    name: Build & Package (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
    
      - name: Setup Visual Studio Build Tools and Windows SDK
        run: |
            choco install visualstudio2022buildtools --params "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --quiet --norestart" -y
        shell: pwsh

      - name: Setup MSBuild (activates environment)
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies
        run: npm ci

      - name: Rebuild sqlite3 for Electron
        shell: pwsh
        env:
          npm_config_disturl: "https://electronjs.org/headers"
          npm_config_runtime: "electron"
        run: |
          $ev = node -p "require('./node_modules/electron/package.json').version"
          Write-Host "Detected electron version: $ev"
          npm install --no-save --no-audit electron-rebuild@3
          npx electron-rebuild -v $ev -f -w sqlite3

      - name: Build (TypeScript / app)
        shell: pwsh
        run: |
          $hasBuild = node -e "try { console.log(Boolean(require('./package.json').scripts && require('./package.json').scripts.build)); } catch (e) { console.log(false); }"
          if ($hasBuild -eq 'true') { npm run build } else { Write-Host "No build script defined" }

      - name: Package Windows EXE
        env:
          CI: true
        run: |
          # This runs your packaging command; it should produce the installer/exe in dist/ or similar
          npm run pack:win

      - name: List dist output (for debugging)
        run: dir /s /b dist || echo "dist folder not found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/**
            out/**

  release:
    name: Create GitHub Release (only on push to main)
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: release_files

      - name: List release_files (debug)
        run: dir /s /b release_files || echo "no release files"

      - name: Create GitHub release and upload assets
        # ncipollo/release-action will create (or update) a release and attach files
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          files: release_files/**
